using SimpleTypeScript.TypeGeneration;
using SimpleTypeScript.TypeGeneration.Modules;
using Xunit;

namespace SimpleTypeScript.Tests;

/// <summary>
/// Discovering modules, writing them, and refusing where the result would be a file nobody notices is wrong.
/// A generated module is written on every build and read by a compiler before a person, so the pipeline's job
/// on a bad day is to stop the build rather than to produce something.
/// </summary>
public sealed class ModulePipelineTests : IDisposable
{
    private readonly string _output =
        Directory.CreateTempSubdirectory(nameof(ModulePipelineTests)).FullName;

    public void Dispose() => Directory.Delete(_output, recursive: true);

    private ModuleWriter Writer(GeneratedHeader? header = null) => new(_output, header);

    [Fact]
    public void Writes_a_module_where_it_says_it_belongs_and_reports_what_it_said()
    {
        var written = Writer(GeneratedHeader.None).Write(new StubModule());

        Assert.Equal("nested/stub.generated.ts", written.FileName);
        Assert.Equal("1 thing", written.Summary);
        Assert.Equal("export const X = \"v\";\n", File.ReadAllText(written.Path), ignoreLineEndingDifferences: false);
    }

    /// <summary>
    /// The directory is the consumer's own source tree, so a module names a path in it and the write creates
    /// what is missing — a clean checkout has no generated folders at all.
    /// </summary>
    [Fact]
    public void Creates_the_directory_a_module_names_but_not_the_root_it_was_given()
    {
        Writer(GeneratedHeader.None).Write(new StubModule());

        Assert.True(Directory.Exists(Path.Combine(_output, "nested")));
        Assert.Throws<GenerationException>(() => new ModuleWriter(Path.Combine(_output, "absent")));
    }

    /// <summary>
    /// A file the generator has stopped producing stays importable, and a stale shape is the one nobody
    /// notices — so a module that owns its directory gets it emptied first, and one that does not must not.
    /// </summary>
    [Fact]
    public void Empties_the_directory_only_for_a_module_that_owns_it()
    {
        var directory = Directory.CreateDirectory(Path.Combine(_output, "nested"));
        var leftover = Path.Combine(directory.FullName, "stale.ts");

        File.WriteAllText(leftover, "export const gone = 1;");
        Writer(GeneratedHeader.None).Write(new StubModule());
        Assert.True(File.Exists(leftover));

        File.WriteAllText(leftover, "export const gone = 1;");
        Writer(GeneratedHeader.None).Write(new OwningModule());
        Assert.False(File.Exists(leftover));
    }

    /// <summary>
    /// The output directory is the consumer's own source tree. A module that owns its directory has it
    /// emptied before the write, so one naming a file directly under the root would take the root — every
    /// hand-written file beside it included, and the write still reports success.
    /// </summary>
    [Fact]
    public void Refuses_to_own_the_output_directory_itself()
    {
        var keep = Path.Combine(_output, "hand-written.ts");
        File.WriteAllText(keep, "export const keep = 1;");

        Assert.Throws<GenerationException>(() => Writer(GeneratedHeader.None).Write(new RootOwningModule()));
        Assert.True(File.Exists(keep));
    }

    /// <summary>A module names a path under the root, and one that climbs out of it is not one.</summary>
    [Fact]
    public void Refuses_a_file_name_that_resolves_outside_the_output_directory()
    {
        // A root inside the fixture's own directory, so where a climb would land belongs to this test rather
        // than to whatever else shares the one above it.
        var root = Directory.CreateDirectory(Path.Combine(_output, "root")).FullName;

        var refusal = Assert.Throws<GenerationException>(
            () => new ModuleWriter(root, GeneratedHeader.None).Write(new EscapingModule()));

        Assert.Contains("outside the output directory", refusal.Message, StringComparison.Ordinal);
        Assert.False(File.Exists(Path.Combine(_output, "climbed-out.ts")));
    }

    [Fact]
    public void Opens_a_module_with_the_banner_the_header_writes()
    {
        var written = Writer(new AssemblyGeneratedHeader(typeof(ModulePipelineTests).Assembly))
            .Write(new StubModule());

        Assert.StartsWith(
            "// GENERATED by SimpleTypeScript.Tests — do not edit.\n// Source: a fixture.\n",
            File.ReadAllText(written.Path),
            StringComparison.Ordinal);
    }

    /// <summary>
    /// One thing to catch. What the emitter refuses underneath the pipeline is the same event to whoever is
    /// watching a build, and the sentence has to survive the wrapping or the refusal stops being readable.
    /// </summary>
    [Fact]
    public void Arrives_as_one_failure_whichever_half_refused()
    {
        var refusal = Assert.Throws<GenerationException>(() => Writer().Write(new EmptyModule()));

        Assert.IsType<TypeScriptException>(refusal.InnerException);
        Assert.Contains("declares nothing", refusal.Message, StringComparison.Ordinal);

        Assert.Throws<GenerationException>(() => Writer().Write(new RefusingModule()));
    }

    /// <summary>
    /// Discovery is what makes adding a generator one class and no edit to a registry. It has to reach an
    /// internal type, since a module is an implementation detail of the generator that declares it.
    /// </summary>
    [Fact]
    public void Finds_every_module_an_assembly_declares_in_one_order()
    {
        var modules = ModuleCatalog.From(typeof(ModulePipelineTests).Assembly);

        Assert.Contains(modules, module => module is StubModule);
        Assert.Contains(modules, module => module is InternalModule);
        Assert.Equal(
            modules.Select(module => module.FileName).OrderBy(name => name, StringComparer.Ordinal),
            modules.Select(module => module.FileName));
    }

    [Fact]
    public void Refuses_an_assembly_that_would_write_nothing()
    {
        Assert.Throws<GenerationException>(() => ModuleCatalog.From(typeof(TsModule).Assembly));
    }

    /// <summary>The common case: a module is its roots, and the walk is the rest.</summary>
    [Fact]
    public void Builds_a_type_module_from_its_roots_alone()
    {
        var written = Writer(GeneratedHeader.None).Write(new TypesFixtureModule());

        Assert.Equal("2 type(s)", written.Summary);
        Assert.Contains("export interface Shape {", File.ReadAllText(written.Path), StringComparison.Ordinal);
    }

    private sealed class StubModule : IGeneratedModule
    {
        public string FileName => "nested/stub.generated.ts";

        public string Source => "a fixture";

        public string Build(TsModule module)
        {
            module.Const("X", TsValue.String("v"));

            return "1 thing";
        }
    }

    private sealed class OwningModule : IGeneratedModule
    {
        public string FileName => "nested/owned.generated.ts";

        public string Source => "a fixture";

        public bool OwnsDirectory => true;

        public string Build(TsModule module)
        {
            module.Const("X", TsValue.String("v"));

            return "1 thing";
        }
    }

    private sealed class RootOwningModule : IGeneratedModule
    {
        public string FileName => "index.generated.ts";

        public string Source => "a fixture";

        public bool OwnsDirectory => true;

        public string Build(TsModule module)
        {
            module.Const("X", TsValue.String("v"));

            return "1 thing";
        }
    }

    private sealed class EscapingModule : IGeneratedModule
    {
        public string FileName => "../climbed-out.ts";

        public string Source => "a fixture";

        public string Build(TsModule module)
        {
            module.Const("X", TsValue.String("v"));

            return "1 thing";
        }
    }

    private sealed class EmptyModule : IGeneratedModule
    {
        public string FileName => "nested/empty.generated.ts";

        public string Source => "a fixture";

        public string Build(TsModule module) => "nothing";
    }

    private sealed class RefusingModule : IGeneratedModule
    {
        public string FileName => "nested/refusing.generated.ts";

        public string Source => "a fixture";

        public string Build(TsModule module) => throw new GenerationException("the source did not hold");
    }

    private sealed class TypesFixtureModule : TypeModule
    {
        public override string FileName => "nested/types.generated.ts";

        public override string Source => "a fixture";

        protected override IEnumerable<Type> Roots => [typeof(Shape)];
    }

    private sealed class Shape
    {
        public Corner Corner { get; init; } = new();
    }

    private sealed class Corner
    {
        public int Angle { get; init; }
    }

    /// <summary>Internal on purpose: discovery has to reach it without being told.</summary>
    private sealed class InternalModule : IGeneratedModule
    {
        public string FileName => "nested/internal.generated.ts";

        public string Source => "a fixture";

        public string Build(TsModule module)
        {
            module.Const("Y", TsValue.Number(1));

            return "1 thing";
        }
    }
}
