using System.Reflection;

namespace SimpleTypeScript.TypeGeneration.Modules;

/// <summary>
/// "GENERATED by … — do not edit." followed by what it was generated from.
/// <para>
/// The generator is named by its <em>assembly</em> rather than by a path to it, so a project renamed or moved
/// takes the header with it instead of leaving one that points at nothing. A "regenerate with …" line is
/// deliberately absent: it would name a build script that no reference reaches, so it could only be kept true
/// by a test — machinery protecting an instruction whoever reads the file has already run.
/// </para>
/// </summary>
public sealed class AssemblyGeneratedHeader : GeneratedHeader
{
    private readonly string _generator;

    /// <summary>Names <paramref name="generator"/>, or the entry assembly where none is given.</summary>
    public AssemblyGeneratedHeader(Assembly? generator = null) =>
        _generator = (generator ?? Assembly.GetEntryAssembly())?.GetName().Name ?? "a generator";

    /// <inheritdoc />
    public override TsComment For(string source) => TsComment.Lines(
    [
        string.Format(Headers.Assembly, _generator),
        string.Format("Source: {0}.", source),
    ]);
}
