namespace SimpleTypeScript.TypeGeneration.Modules;

/// <summary>
/// The comment every generated module opens with. The emitter knows the plainest form of one, since a module
/// it builds is generated by definition; what lives here is everything a banner can say <em>beyond</em> that
/// — which generator wrote the file and what it read — none of which the emitter has any way to know.
/// </summary>
public abstract class GeneratedHeader
{
    /// <summary>The header for a module generated from <paramref name="source"/>.</summary>
    public abstract TsComment For(string source);

    /// <summary>
    /// Names the generator by its own assembly, which is <see cref="AssemblyGeneratedHeader"/> over the entry
    /// assembly — what a build-time tool wants without saying so.
    /// </summary>
    public static GeneratedHeader Default { get; } = new AssemblyGeneratedHeader();

    /// <summary>No banner at all, for output that carries its provenance some other way.</summary>
    public static GeneratedHeader None { get; } = new NoHeader();

    private sealed class NoHeader : GeneratedHeader
    {
        public override TsComment For(string source) => TsComment.Lines([]);
    }
}
